CREATE TABLE [sqlmesh__hook].[hook__frame__northwind__products__3676776232] (

	[_pit_hook__product__id] varchar(max) NULL, 
	[_hook__product__id] varchar(max) NULL, 
	[_hook__supplier__id] varchar(max) NULL, 
	[_hook__category__id] varchar(max) NULL, 
	[_hook__category_detail__id] varchar(max) NULL, 
	[product_id] bigint NULL, 
	[product_name] varchar(8000) NULL, 
	[supplier_id] bigint NULL, 
	[category_id] bigint NULL, 
	[quantity_per_unit] varchar(8000) NULL, 
	[unit_price] float NULL, 
	[units_in_stock] bigint NULL, 
	[units_on_order] bigint NULL, 
	[reorder_level] bigint NULL, 
	[discontinued] bit NULL, 
	[_dlt_load_id] varchar(8000) NULL, 
	[_dlt_id] varchar(8000) NULL, 
	[_record__hash] varbinary(8000) NULL, 
	[_record__loaded_at] datetime2(6) NULL, 
	[_record__updated_at] datetime2(6) NULL, 
	[_record__valid_from] datetime2(6) NULL, 
	[_record__valid_to] datetime2(6) NULL, 
	[_record__is_current] int NULL, 
	[_record__version] bigint NULL
);