CREATE TABLE [sqlmesh__hook].[hook__frame__northwind__suppliers__1398771683__dev] (

	[_pit_hook__supplier__id] varchar(max) NULL, 
	[_hook__supplier__id] varchar(max) NULL, 
	[_hook__region__id] varchar(max) NULL, 
	[supplier_id] bigint NULL, 
	[company_name] varchar(8000) NULL, 
	[contact_name] varchar(8000) NULL, 
	[contact_title] varchar(8000) NULL, 
	[address] varchar(8000) NULL, 
	[city] varchar(8000) NULL, 
	[postal_code] varchar(8000) NULL, 
	[country] varchar(8000) NULL, 
	[phone] varchar(8000) NULL, 
	[_dlt_load_id] varchar(8000) NULL, 
	[_dlt_id] varchar(8000) NULL, 
	[region] varchar(8000) NULL, 
	[home_page] varchar(8000) NULL, 
	[fax] varchar(8000) NULL, 
	[_record__hash] varbinary(8000) NULL, 
	[_record__loaded_at] datetime2(6) NULL, 
	[_record__updated_at] datetime2(6) NULL, 
	[_record__valid_from] datetime2(6) NULL, 
	[_record__valid_to] datetime2(6) NULL, 
	[_record__is_current] int NULL, 
	[_record__version] bigint NULL
);