CREATE TABLE [sqlmesh__hook].[hook__frame__northwind__customers__170116637__dev] (

	[_pit_hook__customer__id] varchar(max) NULL, 
	[_hook__customer__id] varchar(max) NULL, 
	[_hook__customer__name] varchar(max) NULL, 
	[customer_id] varchar(max) NULL, 
	[company_name] varchar(max) NULL, 
	[contact_name] varchar(max) NULL, 
	[contact_title] varchar(max) NULL, 
	[address] varchar(max) NULL, 
	[city] varchar(max) NULL, 
	[postal_code] varchar(max) NULL, 
	[country] varchar(max) NULL, 
	[phone] varchar(max) NULL, 
	[fax] varchar(max) NULL, 
	[_dlt_load_id] varchar(max) NULL, 
	[_dlt_id] varchar(max) NULL, 
	[region] varchar(max) NULL, 
	[_record__hash] varchar(max) NULL, 
	[_record__loaded_at] datetime2(6) NULL, 
	[_record__updated_at] datetime2(6) NULL, 
	[_record__valid_from] datetime2(6) NULL, 
	[_record__valid_to] datetime2(6) NULL, 
	[_record__version] bigint NULL, 
	[_record__is_current] int NULL
);