CREATE TABLE [sqlmesh__hook].[hook__frame__northwind__employees__2643501422] (

	[_pit_hook__employee__id] varchar(max) NULL, 
	[_hook__employee__id] varchar(max) NULL, 
	[employee_id] bigint NULL, 
	[last_name] varchar(max) NULL, 
	[first_name] varchar(max) NULL, 
	[title] varchar(max) NULL, 
	[title_of_courtesy] varchar(max) NULL, 
	[birth_date] datetime2(6) NULL, 
	[hire_date] datetime2(6) NULL, 
	[address] varchar(max) NULL, 
	[city] varchar(max) NULL, 
	[region] varchar(max) NULL, 
	[postal_code] varchar(max) NULL, 
	[country] varchar(max) NULL, 
	[home_phone] varchar(max) NULL, 
	[extension] varchar(max) NULL, 
	[photo] varchar(max) NULL, 
	[notes] varchar(max) NULL, 
	[reports_to] bigint NULL, 
	[photo_path] varchar(max) NULL, 
	[_dlt_load_id] varchar(max) NULL, 
	[_dlt_id] varchar(max) NULL, 
	[_record__hash] varbinary(8000) NULL, 
	[_record__loaded_at] datetime2(6) NULL, 
	[_record__updated_at] datetime2(6) NULL, 
	[_record__valid_from] datetime2(6) NULL, 
	[_record__valid_to] datetime2(6) NULL, 
	[_record__version] bigint NULL, 
	[_record__is_current] int NULL
);