gateways:
  fabric:
    connection:
      type: mssql
      host: {{ env_var('FABRIC__SQL__HOST') }}
      database: {{ env_var('FABRIC__SQL__DATABASE') }}
      user: {{ env_var('AZURE_CLIENT_ID') }}
      password: {{ env_var('AZURE_CLIENT_SECRET') }}
      driver: pyodbc
      driver_name: ODBC Driver 18 for SQL Server
      odbc_properties:
        Authentication: ActiveDirectoryServicePrincipal
    
    state_connection:
      type: mssql
      host: {{ env_var('FABRIC__SQL__HOST') }}
      database: {{ env_var('FABRIC__SQL__DATABASE') }}
      user: {{ env_var('AZURE_CLIENT_ID') }}
      password: {{ env_var('AZURE_CLIENT_SECRET') }}
      driver: pyodbc
      driver_name: ODBC Driver 18 for SQL Server
      odbc_properties:
        Authentication: ActiveDirectoryServicePrincipal

default_gateway: fabric

model_defaults:
  dialect: duckdb
  start: 2025-05-09