[project]
name = "fabric"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.0, <3.12"
dependencies = [
    "dlt[az,deltalake,filesystem,parquet]>=1.12.1",
    "enlighten>=1.14.1",
    "networkx>=3.5",
    "sqlmesh[fabric, lsp, web] @ git+https://github.com/mattiasthalen/sqlmesh.git@feat/add-fabric-engine",
]

[tool.uv]
override-dependencies = [
    "sqlglot @ git+https://github.com/mattiasthalen/sqlglot@fix/fabric-ensure-varchar-max"
]