CREATE TABLE [sqlmesh__scd].[scd__scd__northwind__employees__4109527800] (

	[employee_id] bigint NULL, 
	[last_name] varchar(8000) NULL, 
	[first_name] varchar(8000) NULL, 
	[title] varchar(8000) NULL, 
	[title_of_courtesy] varchar(8000) NULL, 
	[birth_date] datetime2(6) NULL, 
	[hire_date] datetime2(6) NULL, 
	[address] varchar(8000) NULL, 
	[city] varchar(8000) NULL, 
	[region] varchar(8000) NULL, 
	[postal_code] varchar(8000) NULL, 
	[country] varchar(8000) NULL, 
	[home_phone] varchar(8000) NULL, 
	[extension] varchar(8000) NULL, 
	[photo] varchar(8000) NULL, 
	[notes] varchar(8000) NULL, 
	[reports_to] bigint NULL, 
	[photo_path] varchar(8000) NULL, 
	[_dlt_load_id] varchar(8000) NULL, 
	[_dlt_id] varchar(8000) NULL, 
	[_record__hash] varbinary(8000) NULL, 
	[_record__loaded_at] datetime2(6) NULL, 
	[_record__valid_from] datetime2(6) NULL, 
	[_record__valid_to] datetime2(6) NULL
);